server:
  port: 8080

spring:
  profiles:
    active: test

api:
  starwars: "https://swapi.dev/api/"

---


spring:
  data:
    mongodb:
      database: reservasdb
      host: localhost
      port: 27017
  config:
    activate:
      on-profile: dev

---

spring:
  data:
    mongodb:
      database: reservasdb-test
      host: localhost
      port: 27017
  config:
    activate:
      on-profile: test
